link: "Link(" link_first link_rest? ")"

?link_first: link|NUMBER

?link_rest: ", " link

%ignore /\s+/
%import common.NUMBER


tree_node: "Tree(" label branches? ")"

?label: NUMBER

branches:", [" (tree_node ",")* tree_node "]"

%ignore /\s+/
%import common.NUMBER


rstring: "r\"" regex* "\""

?regex: group | pipe | character | word | class

group: "(" regex ")"
pipe: regex "|" regex

class: "["(range | character)+"]"
range: (LETTER "-" LETTER) | (NUMBER "-" NUMBER)

character: LETTER | NUMBER
word: WORD

%ignore /\s+/
%import common.LETTER
%import common.NUMBER
%import common.WORD

